services:
  valkey:
    env_file: .env
    image: valkey/valkey:8.1.1-alpine
    environment:
      QUEUE_DB_PORT: ${QUEUE_DB_PORT}
    ports:
      - "${QUEUE_DB_PORT}:6379"
    volumes:
      - valkey_data:/data
    restart: always

volumes:
  valkey_data: