services:
  queue:
    env_file: .env
    image: valkey/valkey:8.1.1-alpine
    environment:
      QUEUE_PORT: ${QUEUE_PORT}
    ports:
      - "${QUEUE_PORT}:6379"
    volumes:
      - queue-data:/data
    restart: unless-stopped

volumes:
  queue-data: