services:
  queue:
    image: valkey/valkey:8.1.1-alpine
    env_file: .env
    ports:
      - "${QUEUE_PORT}:6379"
    volumes:
      - queue-data:/data
    restart: unless-stopped

  mongo:
    image: mongo:8.0
    logging:
      options:
        max-size: 1g
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - local
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    env_file: .env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
        test: curl -s http://localhost:9200/_cluster/health | grep -q '"status"' || exit 1
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      - local
    restart: unless-stopped

volumes:
  queue-data:
  mongo-data:
  elasticsearch-data:

networks:
  local:
    driver: bridge