# YouTube Video Indexer Documentation

site_name: YouTube Video Indexer
site_description: Event-driven YouTube content indexing system with PubSubHubbub integration
site_author: maikereis
repo_url: https://github.com/maikereis/youtube-video-indexer
repo_name: maikereis/youtube-video-indexer

# Theme configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.pathdocs/architecture
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Configuration: getting-started/configuration.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Architecture:
    - System Overview: architecture/overview.md
    - Data Flow: architecture/data-flow.md
    - Services: architecture/services.md
    - Scaling: architecture/scaling.md
    - Data Stores: architecture/data-stores.md
  - Doc:
    - Database: documentation/database.md
    - Queues: documentation/queues.md
    - Worker: documentation/worker.md
    - Indexer: documentation/indexer.md
    - API: documentation/api.md

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - mkdocstrings
  - git-committers:
      repository: maikereis/youtube-video-indexer
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true


# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/maikereis/youtube-video-indexer
  generator: false

# Copyright
copyright: Copyright &copy; 2024 maikereis
